---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: amazon-prime
  template:
    metadata:
      labels:
        app: amazon-prime
    spec:
      containers:
      - name: amazon-prime-container
        image: sanjaysaravanan1/amazon-prime
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-service
spec:
  type: LoadBalancer
  selector:
    app: amazon-prime
  ports:
  - port: 80
    targetPort: 3000
